name: hashfields
version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    entrypoint: []
    image: hashfields:dev
    volumes:
      - .:/home/calitp/hashfields

  dist:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dist
    image: hashfields:dist

  docs:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.docs
    image: hashfields:docs
    ports:
      - "8000"
    volumes:
      - .:/docs
