version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    entrypoint: []
    environment:
      - DOTNET_ENVIRONMENT=Development
    image: hashfields:dev
    volumes:
      - .:/home/calitp/hashfields

  deploy-alpine:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.deploy
      args:
        - runtime=6.0-alpine
        - target=linux-musl-x64
    command: ["./hashfields"]
    environment:
      - DOTNET_ENVIRONMENT=Production
    image: hashfields:deploy-alpine

  docs:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.docs
    image: hashfields:docs
    ports:
      - "8000"
    volumes:
      - .:/docs
