version: "3.8"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: hashfields:dev
    entrypoint: []
    command: sleep infinity
    working_dir: /hashfields
    volumes:
        - ..:/hashfields
