FROM python:3.11 as builder

WORKDIR /builder

COPY . .
RUN pip install -e .[dist]
RUN pyinstaller --onefile pyinstaller_entrypoint.py --name hashfields

FROM python:3.11

WORKDIR /hashfields
COPY --from=builder /builder/dist/* .
RUN chmod +x ./hashfields

ENTRYPOINT ["./hashfields"]
