name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - "202[2-9].0[1-9].[1-9]" # 2022.02.2
      - "202[2-9].0[1-9].[1-9][0-9]" # 2022.02.22
      - "202[2-9].1[0-2].[1-9]" # 2022.11.1
      - "202[2-9].1[0-2].[1-9][0-9]" # 2022.11.11

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [linux-x64, win10-x64, osx.11.0-x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version-file: .github/workflows/.python-version
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: Install package
        run: pip install -e .[test,dist]

      - name: Test
        run: ./bin/coverage.sh

      - name: Package
        run: ./bin/package.sh

      - name: Make artifact path
        id: make-path
        env:
          ref: ${{ github.ref }}
          runtime: ${{ matrix.runtime }}
        run: |
          echo "path=hashfields-${ref/refs\/tags\//}-$runtime.zip" >> $GITHUB_OUTPUT

      - name: Zip
        env:
          path: ${{ steps.make-path.outputs.path }}
        run: |
          zip -r -j $path dist/
          ls -l $path

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.make-path.outputs.path }}

  release:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: package
          path: ./package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./package/*.zip"
