name: Publish release

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [5.0.x]
        runtime: [linux-x64, win10-x64, osx.11.0-x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tooling
        run: sudo apt-get install -qq zip

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -r ${{ matrix.runtime }} -c Release -o ./out src/Cli/hashfields.csproj

      - name: Zip
        run: |
          zip -r -j hashfields-${{ matrix.runtime }}-${{ matrix.dotnet }}.zip out/
          ls -l hashfields-${{ matrix.runtime }}-${{ matrix.dotnet }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: hashfields-${{ matrix.runtime }}-${{ matrix.dotnet }}.zip

  release:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ./package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./package/*.zip"
