name: Publish release

on:
  push:
    tags:
      - "202[2-9].0[1-9].[1-9]" # 2022.02.2
      - "202[2-9].0[1-9].[1-9][0-9]" # 2022.02.22
      - "202[2-9].1[0-2].[1-9]" # 2022.11.1
      - "202[2-9].1[0-2].[1-9][0-9]" # 2022.11.11

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [6.0.x]
        runtime: [linux-x64, win10-x64, osx.11.0-x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tooling
        run: sudo apt-get install -qq zip

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -r ${{ matrix.runtime }} -c Release -o ./out src/Cli/hashfields.csproj

      - name: Make artifact path
        id: make-path
        env:
          ref: ${{ github.ref }}
          runtime: ${{ matrix.runtime }}
          dotnet: ${{ matrix.dotnet }}
        run: |
          echo "::set-output name=path::hashfields-${ref/refs\/tags\//}-$runtime-dotnet-$dotnet.zip"

      - name: Zip
        env:
          path: ${{ steps.make-path.outputs.path }}
        run: |
          zip -r -j $path out/
          ls -l $path

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.make-path.outputs.path }}

  release:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ./package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./package/*.zip"
