name: pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dotnet dependencies
        run: dotnet restore

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: "**/requirements.txt"

      - name: Install python dependencies
        run: pip install -r .devcontainer/requirements.txt

      - name: Run tests
        run: pytest
